
spring:
  application:
    name: cadastro-prestador
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    
iart-config-server:
  name: "gustavo"
  lastname: "santos - dev"    